### ISSUE TITLE
really out of date

### ISSUE THREAD

**Issue by tzz** [nickanderson/CFEngine-3-by-example-vagrant#8]

**Comment by nickanderson** [comment]
YES IT IS I stick to using https://docs.cfengine.com/latest/guide-installation-and-configuration-general-installation-installation-enterprise-vagrant.html these days. Perhaps I will update this sometime .

**Comment by tzz** [comment]
...you could update the README dude :)

**Comment by nickanderson** [comment]
https://github.com/nickanderson/CFEngine-3-by-example-vagrant/commit/074f5b4205d5ddc4fd163a2ad196ea9a4ac3b9b6
